package com.feuch.clochette

internal fun String.withVisibleFrenchAccents(): String = this
    .replace(" ca ", " ça ")
    .replace(" Ca ", " Ça ")
    .replace("deja", "déjà")
    .replace("Deja", "Déjà")
    .replace("idee", "idée")
    .replace("Idee", "Idée")
    .replace("idees", "idées")
    .replace("Idees", "Idées")
    .replace("telephone", "téléphone")
    .replace("Telephone", "Téléphone")
    .replace("foret", "forêt")
    .replace("Foret", "Forêt")
    .replace("decision", "décision")
    .replace("Decision", "Décision")
    .replace("detours", "détours")
    .replace("Detours", "Détours")
    .replace("peut-etre", "peut-être")
    .replace("Peut-etre", "Peut-être")
    .replace("reponse", "réponse")
    .replace("Reponse", "Réponse")
    .replace("detectee", "détectée")
    .replace("Detectee", "Détectée")
    .replace("detecte", "détecté")
    .replace("Detecte", "Détecté")
    .replace("numerique", "numérique")
    .replace("Numerique", "Numérique")
    .replace("energie", "énergie")
    .replace("Energie", "Énergie")
    .replace("ecran", "écran")
    .replace("Ecran", "Écran")
    .replace("entree", "entrée")
    .replace("Entree", "Entrée")
    .replace("soupconne", "soupçonne")
    .replace("Soupconne", "Soupçonne")
    .replace("negocie", "négocie")
    .replace("Negocie", "Négocie")
    .replace("lisibilite", "lisibilité")
    .replace("Lisibilite", "Lisibilité")
